---
kind: pipeline
name: validate

platform:
  os: linux
  arch: amd64

steps:
  - name: Verify
    image: maven:3.6-slim
    commands:
      - mvn verify

trigger:
  branch:
    exclude:
      - release/*

---
kind: pipeline
name: deploy

platform:
  os: linux
  arch: amd64

steps:
  - name: Deploy to Bintray
    image: maven:3.6-slim
    environment:
      MAVEN_USERNAME: mwl
      MAVEN_PASSWORD:
        from_secret: bintray_password
    commands:
      - mkdir -p ~/.m2
      - >
        echo '<?xml version="1.0" encoding="UTF-8"?>
        <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd">
          <servers>
            <server>
              <id>bintray-humio-Maven</id>
              <username>$${MAVEN_USERNAME}</username>
              <password>$${MAVEN_PASSWORD}</password>
            </server>
          </servers>
        </settings>' > ~/.m2/settings.xml
      - mvn deploy

trigger:
  branch:
    - release/*
  event:
    - tag

...
