/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_humio_jitrex_PerformanceTest_RustRegexBackend */

#ifndef _Included_com_humio_jitrex_PerformanceTest_RustRegexBackend
#define _Included_com_humio_jitrex_PerformanceTest_RustRegexBackend
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_humio_jitrex_PerformanceTest_RustRegexBackend
 * Method:    internalCountMatches
 * Signature: (Ljava/lang/String;[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_humio_jitrex_PerformanceTest_00024RustRegexBackend_internalCountMatches
  (JNIEnv *, jclass, jstring, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
