name: Verify build

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        java: ['8.x', '11.x', '13.x']
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Build with Maven on Java ${{ matrix.java }}
        run: mvn verify
